AllCops:
  Include:
    - Rakefile
    - geo_api.rb
  Exclude:
    - data/**
    - config/**
    - features/**
    - spec/**
    - reports/**
    - vendor/**
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
AndOr:
  Enabled: false
LineLength:
  Enabled: true
  Max: 165
